# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e97825fbc4e26eda576d372a003f8a3d42ece3b9f5e30e6af0c48c8e40c5196ec6c7eb124f1267afb4af90ed163512490868ed530e62ce8ef79c3b985b04e3db

test:
  secret_key_base: d23a7608aa7b96574204a990d5ada173606ee8be0c95e6cbe524db704098593d6b4a062c6f3880152e393a981eeacff1bb1f05c0f1291499713ace00d2509eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
